SELECT COMPANY_ID FROM ConsitiPOS.COMPANY;
SELECT * FROM ConsitiPOS.CUSTOMER;
SELECT * FROM ConsitiPOS.METRIC;
SELECT * FROM ConsitiPOS.MISSING_TRAN;
SELECT * FROM ConsitiPOS.REFERENCE;
SELECT * FROM ConsitiPOS.ROLE_FIELD;
SELECT* FROM ConsitiPOS.STORE;


ALTER TABLE ConsitiPOS.ITEM_MASTER ADD COLUMN COMPANY_ID INT;
ALTER TABLE ConsitiPOS.CUSTOMER ADD COLUMN COMPANY_ID INT;
ALTER TABLE ConsitiPOS.METRIC ADD COLUMN COMPANY_ID INT;
ALTER TABLE ConsitiPOS.MISSING_TRAN ADD COLUMN COMPANY_ID INT;
ALTER TABLE ConsitiPOS.REFERENCE ADD COLUMN COMPANY_ID INT;
ALTER TABLE ConsitiPOS.ROLE_FIELD ADD COLUMN COMPANY_ID INT;
ALTER TABLE ConsitiPOS.STORE ADD COLUMN COMPANY_ID INT;
